### ISSUE TITLE
Put timestamp in PDF

### ISSUE THREAD

**Issue by campos20** [thewca/tnoodle#232]
This was requested by @Luis-J-Ianez, via email (about another subject)
> could we have not only the date but also the generation time, accurate to seconds, printed in the sheets?  That would help detect possible abuses by replacing the legal scrambles with others.  Or does this sound crazy?

@jfly answered in the same email discussion:
> That's certainly possible, Luis. However, it really only protects us from people who are not competent enough to spoof the PDFs (which is a very easy thing to do). The only secure solution would be for the WCA website to start generating scrambles, which might be a good direction for us to go, but would be a ton of engineering effort.

I decided to open this issue to help in this discussion, see pros and cons.

**Comment by campos20** [comment]
Before
![captura de tela de 2017-01-04 15-29-35](https://cloud.githubusercontent.com/assets/10170850/21652145/ac80fd64-d292-11e6-9d6f-d9c9974e3fe5.png)

Suggestion
![captura de tela de 2017-01-04 15-26-49](https://cloud.githubusercontent.com/assets/10170850/21652066/480fdbe8-d292-11e6-8a81-d384979acdd0.png)

**Comment by Laura-O** [comment]
If we add a timestamp it should not be understandable by the average competitor (e.g. a Unix timestamp). I a quite sure that a human readable timestamp will confuse some competitors.

**Comment by campos20** [comment]
Interesting suggestion. But if it's not human readable, it may not prevent cheating, as requested by Luis. If someone sees 1483550649 (timestamp in milliseconds, as used in Unix and others) and 1461950649, is it clear the 6 hours difference? The cheater can just print his/her own version using standard TNoodle, no one will care to remember all the digits. Remembering the final 2 digits, for example, is a bigger effort than remembering naturally when the scrambles were printed. Using understandable time, the delegate may remember when the scrambles were printed and a six hours difference would be noticed.

**Comment by pedrosino** [comment]
> I a quite sure that a human readable timestamp will confuse some competitors.

Why would it confuse competitors?

**Comment by Laura-O** [comment]
> Why would it confuse competitors?

Because they might understand this as the current date and not the date the scrambles were generated at.

Apart from that, which kind of cheating do we want to prevent here? Competitors bringing their own FMC sheet to a competition?
As Luis mentioned in his mail, this is rather crazy. It will be easy to identify an exchanged scrambles for several reasons. And if someone checking FMC sheets is not noticing a different scramble I doubt that he/she is noticing a different timestamp.

**Comment by jfly** [comment]
> That would help detect possible abuses by replacing the legal scrambles with others

It might also be worth noting that one of my big goals for the WCA website is to eventually require uploading FMC solutions to the website, which means the WCA Results Team would then be able to detect phony solutions.

**Comment by campos20** [comment]
If you search why we have to turn off electronics during flight, you will find that it's because it _may_ cause interference when considered _hundreds_ of trips, although there's no accident reported so far caused by this issue. The cost of asking passengers to turn off the device is very low and the benefits are enormous.

I know we're not dealing with dozens of lives, but to put a stamp that _may_ help to detect cheating (considering that we have _hundreds_ of competitions worldwide) seems low price to me, although I can't think, from the top of my head, of an incident that does not sound crazy.

So, crazy idea:
* The cheater can print a set of sheets in the day before, get used to it (it can be FMC, 3x3x3 or any other) and replace them all, if s/he is picked for scrambler, let's say.

Putting timestamp won't prevent every case, but it may help. It's quite neurotic to ask someone to check this stamp anyways.

> one of my big goals for the WCA website is to eventually require uploading FMC solutions to the website

It sounds like a great solution for the FMC.

**Comment by Luis-J-Ianez** [comment]
Let me clarify this.  I proposed that because it is extremely easy to code and besides, because it could help us in some circumstances.  I agree with Jeremy that it will seldom be of any use, but considering how affordable it is, maybe it would be worthy all the same.  Not to mention the possible dissuasive effect that this could have.

If we are concerned about timestamps confusing people, we could hash the timestamp (date and time to seconds -and maybe even the TNoodle version?) and use the hash or a portion of it like security measure.  Something like:

`Generated by TNoodle-WCA-0.11.5 - Authenticity code = 4EBF86C01C`

**Comment by Laura-O** [comment]
> If you search why we have to turn off electronics during flight, you will find that it's because it may cause interference when considered hundreds of trips, although there's no accident reported so far caused by this issue. The cost of asking passengers to turn off the device is very low and the benefits are enormous.

Well, sorry to say that but the flight analogy is really bad: [the FAA changed this rule](http://edition.cnn.com/2013/10/31/travel/faa-portable-electronic-devices/) and many airlines allow you to use electronics during start and landing now because they realised that there is no problem with radio interference signals. :wink:

But back to topic: don't get me wrong, I am supporting every useful change to prevent cheating, but I like questioning the benefit and the applicability of these changes. This doesn't mean that I am arguing against it.

As said above, I'd prefer a less noticeable and not human-readable timestamp. I like @Luis-J-Ianez suggestion.

**Comment by campos20** [comment]
> the flight analogy is really bad

:smile: Agreed

Anyways, I think any authentication method to detect possible abuses should suffice, specially considering the "dissuasive effect that this could have".

Random numbers/letters or should it contain information to be encrypted and decrypted? How much information, if that's the case, do we want to put in an authentication? An expression can contain time of generation and name of the user (in a pc, let's say, from System.getProperty("user.name")).

**Comment by jfly** [comment]
If we want something short and unpredictable, we could do a hash of the scramble.

**Comment by lgarron** [comment]
> If we want something short and unpredictable, we could do a hash of the scramble (or just a random number).

That sounds trivial to forge.

I don't have time to keep up with this discussion right now, but if it converges on something, please ping me to take a look at the proposed solution and its threat model.

**Comment by jfly** [comment]
The attack Luis was worried about is someone substituting their fmc solution sheet with a prepared one. Unless I'm mistaken,  I don't think "forging" is a relevant word here, it's really easy to forge fmc sheets. I think the idea is to make it easy to check that the solution sheet the competitor handed in is the same as the solution sheet they were given at the start of the round.

**Comment by Luis-J-Ianez** [comment]
I'm not 'especially' worried about FMC.  In fact, in the case the scramble sheets are replaced for cheating, FMC is the event for which this can be more easily detected, as we always keep the sheets.  My first thought was having the timestamp printed and use that as security measure, but after having heard from all you, I think that a short hash based on generation date+time(+tnoodle version?) could help here.  And also a random sequence of numbers and letters, yeah, why not.  Something like "3E72A0", really simple and short, that any attentive scrambler could detect.

I'd use just one security sequence for all the competition, but after several hours of competition we would be exposed to abuse.  On the other hand, if we set a different security sequence for every round or group, recognizing faked sequences would be complicated.

So maybe all this effort is of no use, after all.  Or it would help a bit but not much.  What do you think?

**Comment by Laura-O** [comment]
Well, generating a hash is not that much effort.
However, I would prefer a longer one, maybe 10 or 15 characters so it's more difficult to memorize it.

**Comment by jfly** [comment]
Upon reflection, I don't think this is worth the effort. I personally don't want to handle a bunch of people asking me about this change (and I know they will). Let's focus on getting fmc solutions uploaded to the wca website instead.

@campos20, reach out to me if you would be interested in working on that.
