### ISSUE TITLE
Android Project not recognizing tnoodle-android

### ISSUE THREAD

**Issue by HactarCE** [thewca/tnoodle#233]
I have added the following in my app build.gradle dependencies, but although my project compiles I am unable to import anything from tnoodle:
```
dependencies {
    ....
    compile group: 'com.github.cubing', name: 'tnoodle-android', version: '0.8.9'
}
```

**Comment by starr0stealer** [comment]
The documentation should be updated on how to include this library in an Android project.

ie

```
    compile('com.github.cubing:tnoodle-android:0.8.9@aar') {
        transitive = true
    }

// AndroidManifest.xml  -- shouldnt have to do this :|

<application tools:replace="android:icon">
```

**Comment by jfly** [comment]
@plusCubed, could you comment on this?

**Comment by jfly** [comment]
@starr0stealer, I'll gladly accept a PR adding any such documentation.

**Comment by starr0stealer** [comment]
@jfly I assisted @HactarCE on the IRC channel `#android-dev` with getting the Android package included in their project, haven't used it directly myself. BUT soon as I get some spare time I will create a new Android project and isolate exactly what needs to be done in order to use the Android library.

I'll keep an eye open here to see if someone handles this before I get time.

**Comment by plusCubed** [comment]
The newest version should work, the manifest problem was fixed quite a while ago: 
`compile 'com.github.thewca:tnoodle:v0.11.5'`

**Comment by suushiemaniac** [comment]
Closing this issue because support for the `aar` artifact has been discontinued.

Please use `compile 'com.github.thewca:tnoodle:v0.11.5'` as suggested by @plusCubed until we provide jar artifacts of the core TNoodle scrambling code.
