### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by Julio974** [thewca/tnoodle#240]
I'm not good at programming, and I'd like to know how to run this. How should I run the ``./tmt make run -p wca``? How can I add scrambles, change scrambles names? Thank you for any help!

**Comment by jfly** [comment]
First you'll need to clone the repository (using `git clone`). After that, you should be able to run that `tmt` command you copy pasted. Do all of this inside of a bash terminal on Linux. If you're on windows, I recommend looking into the [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux). If you're on OSX, things might just work for you.

**Comment by jfly** [comment]
Good luck! Feel free to comment on this issue if you have further questions.

**Comment by jfly** [comment]
I'm not familiar with `git install` as a command. Try `git clone`? Also, could you include screenshots of what's happening?

**Comment by Julio974** [comment]
![image](https://user-images.githubusercontent.com/32576200/32134388-b823df12-bbec-11e7-83ed-ebd8e8a4be87.png)
I already used `git install https://github.com/thewca/tnoodle.git`

**Comment by jfly** [comment]
I don't see anything about `git install` in that screenshot.

After you run `git clone`, you're going to need to cd into the newly created `tnoodle` directory and run `./tmt`, which is also not what you did (I see you trying to run `tmt`, not `./tmt`). However, none of this is likely to work well for you because from your screenshot it looks like you're in windows (see my comments in https://github.com/thewca/tnoodle/issues/240#issuecomment-340058175 for what to do about the fact that you're on windows).

**Comment by Julio974** [comment]
But what is the WSL?

**Comment by jfly** [comment]
Did you read my comment here: https://github.com/thewca/tnoodle/issues/240#issuecomment-340058175 ? It provides a link to a document about the WSL.

**Comment by Julio974** [comment]
Yes, but I don't understand how to run it, how to use it...

**Comment by Julio974** [comment]
If I could get some help, it would be useful

**Comment by jfly** [comment]
@Julio974, I suggest you read through a command line tutorial and then a java tutorial before trying to work on TNoodle. Unfortunately, you just need to know some of these basics before you'll be able to work on the codebase. If you have specific questions, I'm happy to answer them here, but generic questions like "I don't understand how to run it, how to use it" are very difficult for me to answer.
