### ISSUE TITLE
React ui crashes on Edge browser with URLSearchParams not defined

### ISSUE THREAD

**Issue by jfly** [thewca/tnoodle#335]
See:

![image](https://user-images.githubusercontent.com/277474/35541212-88e4937a-050e-11e8-959b-d4bba5340493.png)

Can I Use says this is supported in Edge 17: https://caniuse.com/#feat=urlsearchparams, but https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8993198/ says it is fixed, but not yet flighted.

**Comment by suushiemaniac** [comment]
We will get Edge support "for free" in the next few weeks, because Microsoft is actively working on migrating their browser to the Chromium WebKit engine. There has already been a release candidate, and MS seems to be very proactive about pushing that release forward. Keep an eye on tech news and headlines for details.

**Comment by suushiemaniac** [comment]
The Chromium-based Edge update [has been release](https://support.microsoft.com/en-us/help/4501095/download-the-new-microsoft-edge-based-on-chromium).

I will close this bug in favor of prompting people to upgrade their OS and/or browser versions.
