### ISSUE TITLE
Access the new UI without having to organize an official competition

### ISSUE THREAD

**Issue by Julio974-TheHexahedron** [thewca/tnoodle#372]
I'm using Tnoodle for unofficial competitions at my school for almost a year now, and I remarked (by downloading the new version of TNoodle) that the only way to generate scrambles is to use the "Legacy UI".
Could it be possible to make the "WCA" interface accessible to non-organizers?

**Comment by viroulep** [comment]
I'm not sure how familiar you are with managing competitions as organizers on the WCA website, but basically the Delegates/Organizers have a page on the WCA website where they input all the information about events, rounds, formats, and groups.
The "WCA" interface of tnoodle simply generates everything at once based on these information, there is absolutely no way to adjust events/rounds in this new interface.
The only thing we input is the number of scrambles for multi blind (if applicable) and the zip password.

Therefore the new UI is absolutely useless without a competition on the WCA website :s

FYI we still use the legacy UI when we need to generate extra, unexpected, scrambles.

I'm going to close this issue because the new UI is simply not built to be used without an official competition, as it's essentially a wrapper to drastically decrease human mistakes when generating scrambles for a competition.

Feel free to re-open it if you feel I missed something in your request!

**Comment by Julio974-TheHexahedron** [comment]
By what I wrote, I mean putting the new UI on the legacy scrambler. It's just a graphic front-end issue/request (from what I know), so I don't think it should be a priority, but it could be a feature for the next release of that scramble program.

**Comment by viroulep** [comment]
Oh you mean like using the same UI components we used for the new UI to rewrite the legacy UI and make it look nicer?

**Comment by Julio974-TheHexahedron** [comment]
Staging server?

**Comment by Julio974-TheHexahedron** [comment]
And how are we supposed to do that?

**Comment by viroulep** [comment]
The readme is a bit hidden but it's [here](https://github.com/thewca/tnoodle/blob/efb21b3d5d7aa29c14502278f0a604b3014e0c08/tnoodle-ui/README.md#connecting-to-staging-wca-server).

Staging is our [unstable test server](https://staging.worldcubeassociation.org/), it has anonymized production data (date of birth are all 1954-12-04, and passwords are all "wca") and is here for us to test new features.

**Comment by Julio974-TheHexahedron** [comment]
So, changing things on a competition on the staging server doesn't change anything about the true competition?

**Comment by jfly** [comment]
That's correct.
