### ISSUE TITLE
About scrambles for big cubes and megaminx

### ISSUE THREAD

**Issue by moralsh** [thewca/tnoodle#392]
From Ilya Tsiareshka on the Staff group

> After competition YJ Fest Siberia 2019 where was held unofficial event "Scrambling" the main judge of this event Nikita Razzamazov told me about several possible changes for TNoodle. On his opinion these changes can add more convenience for scramblers:
> 1. Each second string is started with a blank space (see attached).
> 2. The first move of each string is colored with different colors.

> I've tried the first option and didn't see significant improving in convenience. For second option I don't see applying in practice. But maybe for someone these proposals will be useful and then we could ask the WST to implement it. What do you think about these proposed changes?

![7x7](https://user-images.githubusercontent.com/12932500/52111332-af574400-2603-11e9-9433-cc906c3c4f38.jpg)
![6x6](https://user-images.githubusercontent.com/12932500/52111333-af574400-2603-11e9-9be2-425d14c0826a.jpg)
![mega](https://user-images.githubusercontent.com/12932500/52111334-af574400-2603-11e9-91ba-8594e48d4aba.jpg)

**Comment by jfly** [comment]
> I've tried the first option and didn't see significant improving in convenience

I agree that this doesn't feel any better than the shaded line we already have. If even the person who suggested this doesn't think it's any better, why are we even considering this?

> The first move of each string is colored with different colors.

What would this look like? I don't see an example of this in the screenshot.

**Comment by suushiemaniac** [comment]
I think that this issue is not relevant for the "everyday use" of TNoodle scrambles.
The original post states that:

> After competition YJ Fest Siberia 2019 where was held unofficial event "Scrambling"

which means that these suggestions were derived from a perspective of someone trying to scramble as fast as possible for the sake of achieving a fast scramble time.

I firmly believe that scramblers at cubing competitions should scramble as **accurate** as possible for the sake of achieving a correct scramble state. I strongly object to the idea of implementing measures that encourage scramblers to parse scramble lines faster and therefore more sloppily.

I'd like to close this issue unless anyone has considerable arguments in favo(u)r of this change. T-3 days to object.
