### ISSUE TITLE
Generate Seperate PDFs for each attempt of FMC and Multi-Blind

### ISSUE THREAD

**Issue by EdHollingdale** [thewca/tnoodle#397]
It would be good to have a different file for each attempt of FMC and Multi. If you print out multiple copies of the FMC scrambles the pages will be in order 1,2,3,1,2,3,1,2,3 instead of 1,1,1   2,2,2   3,3,3 which can lead to a higher potential of accidentally giving someone the wrong scramble. Similarly for multi where multiple copies of the scrambles are often printed, there is a higher potential for operational risk errors by, for example, giving one page from attempt 2 mixed with the attempt 1 scrambles.

**Comment by EdHollingdale** [comment]
I'm just bumping this issue. A WCA Board Member from Australia who will remain anonymous made this error and I had to spend a long time reordering 180*3 FMC sheets - fortunately I was not competing in the event. I assume that this is a trivial fix and it is something that, as I said, reduces the chance for operational risk errors. Even if this is the type of mistake a delegate only makes once in their life (since they'll never forget to do it again!) that is not a reason not to implement it.

**Comment by JonEsparaz** [comment]
I'd also like to bump this. Regarding Multi, in situations where I only compete in Attempt 3 and help scramble for Attempts 1 and 2 (or something similar), it always feels a little sketchy having the scrambles I will be competing on in the same PDF.

**Comment by campos20** [comment]
I'm doing this in about 2 weeks. For now, my idea is to split files just in the encrypted files for security reasons. This way, scramblers from attempt 1 don't get to see scrambles for 2 and 3.

I don't like the idea of changing TNoodle just because of printing order like 1, 1, 1, 2, 2, 2, 3, 3, 3 instead of 1, 2, 3, 1, 2, 3, 1, 2, 3 or other printing stuff because this is already supported by physical printers, PDFs readers/printers for example. You can print just 1 page multiple times even if the file has more pages, you can reverse print, you can resize printing, etc.

The situation you described could be solved by configuring the PDF reader/printer to do 4 copies grouped (ie 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3) or a more boring situation: select just page 1, print 4 times; select just page 2, print 4 times; select just page 3, print 4 times.

Perhaps a WQAC could do a tutorial or something with these explanations.

Anyways, after the change, you can open the split password encrypted file and print it separately.

**Comment by suushiemaniac** [comment]
@campos20 I **strongly** recommend we merge up https://github.com/thewca/tnoodle/pull/421 before you tackle this issue. It contains some changes that make handling of ZIP file contents and PDFs in general much easier.

**Comment by campos20** [comment]
> @campos20 I **strongly** recommend we merge up #421 before you tackle this issue. It contains some changes that make handling of ZIP file contents and PDFs in general much easier.

Good point. I'll wait, testing ktor :)

**Comment by suushiemaniac** [comment]
Now that we have modern infrastructure, we may want to consider implementing this again.
@campos20 Do you still have the resources to work on this?

**Comment by campos20** [comment]
@suushiemaniac perhaps we should wait for the new New UI? It doesn't make much since since we are not passing copies right now...

**Comment by ligio90** [comment]
I can work on this now.

**Comment by campos20** [comment]
@EdHollingdale could you please try the new version? It supports copies.

**Comment by EdHollingdale** [comment]
I generated some scrambles using RC2 (everything worked fine and I love the new UI) but the scrambles for printing (and for computer display) had all fmc attemps and multi attempts in the same pdf when I went to open it. Particuarly for multi on computer display, the attempts should be different files for scramble secrecy as Jon mentioned, and I feel the /Printing/Scramble Sets should have them as different files as well for ease of use.
