### ISSUE TITLE
run command

### ISSUE THREAD

**Issue by LXD312569496** [thewca/tnoodle#538]
How to solve this，I want to a jar to use in Android
![image](https://user-images.githubusercontent.com/20368106/75539280-f442e980-5a54-11ea-949c-72c74a9544d6.png)

**Comment by suushiemaniac** [comment]
Hello,
you are getting this error because you have downloaded a standalone copy of the project. Instead, you should clone the git repository by using something along the lines of `git clone https://github.com/thewca/tnoodle.git`

If you do not want make any modifications, you can also use the pre-compiled artifacts at [Bintray](https://bintray.com/thewca/tnoodle-lib/scrambles). Assuming that your Android project uses Gradle, you can add the dependency like so:

```gradle
dependencies {
  implementation 'org.worldcubeassociation.tnoodle:lib-scrambles:0.17.0'
}
```

**Comment by LXD312569496** [comment]
dependencies {
  implementation 'org.worldcubeassociation.tnoodle:lib-scrambles:0.17.0'
}
it does not work。Can you?

**Comment by suushiemaniac** [comment]
Make sure that your Gradle build is linked to the correct sources as explained in the Bintray page that I linked above.

Our main repository is JCenter, available via:
```gradle
repositories {
    jcenter()
}
```

If that does not work, you can try to hook directly into the Bintray release like so:
```gradle
repositories {
    maven {
        url  "https://dl.bintray.com/thewca/tnoodle-lib" 
    }
}
```

If that _still_ does not work, please provide more feedback than
> it does not work。Can you?

Error messages, screenshots, information about your OS and Java version as well as links to your configuration files are generally helpful. Otherwise I will not be able to help, it's like saying "My car does not start". It could be one of 1000 reasons and I simply do not have the capacities to consider them all.

**Comment by suushiemaniac** [comment]
I have also just updated https://github.com/thewca/tnoodle-samples/tree/master/tnoodle-android/src/main/java/net/gnehzr/tnoodle/androidsample to use the latest Bintray releases, so you can look there if you're unsure about anything.

I have confirmend that that Android build works fine without error.

**Comment by LXD312569496** [comment]
Thank you! it works !
I want to make a cross platform cube app.
And I want to know, how to use this jar into ios project?or how to use it into server

**Comment by suushiemaniac** [comment]
The scrambling code is pure Java. This means it is only supported on Android.

For any other environment, you will need to create some form of API (for example, run the Java code on a web server and install a RESTful interface) that the application can access easily.

Since the original problem was solved (and iOS is definitely not my area of expertise!) I will close this issue now.
