### ISSUE TITLE
Regression Test of PDF generation

### ISSUE THREAD

**Issue by lgarron** [thewca/tnoodle#64]
We should be able to catch that encrypted PDFs are broken, so that [this doesn't happen again](https://github.com/cubing/tnoodle/commit/69f4d6cc89323442f8fae1dfeed8d2e93cf445e1).

**Comment by suushiemaniac** [comment]
We have Gradle now. ;-)

In particular, we don't track external JAR dependencies in the TNoodle `git` anymore. This means that the `itext5` dependency coordinate and the Bouncy Castle releases are responsible for shipping the right things. If stuff like this breaks again,
a) we will not be able to fix it
b) half of the Internet will burn because Bouncy Castle certificates are used in virtually every piece of Java software that does encryption.

T-3 days before I close this issue in favo(u)r of Gradle builds.
