### ISSUE TITLE
unnecessary cube rotations

### ISSUE THREAD

**Issue by eriktks** [thewca/tnoodle#669]
## Actual (problem) behavior
TNoodle adds unnecessary cube rotations to the scrambles of the event 4x4x4 Blindfolded while it does not do so for the events 3x3x3 Blindfolded, 5x5x5 Blindfolded and plain 4x4x4

## Expected behavior
No cube rotations should be added to the scrambles of the event 4x4x4 Blindfolded

## Steps To Reproduce
1. Start TNoodle
2. Select event 4x4x4 Blindfolded
3. Generate scrambles
4. Inspect scrambles

## Desktop:
- Tested with TNoodle Version 1.1.0
- Applies to any OS, any browser, any Java version

## Screenshots:
![screenshot](https://user-images.githubusercontent.com/3670455/117636351-018f5400-b181-11eb-8be2-aa3b37deb2d0.png)

## Additional context:
None

**Comment by suushiemaniac** [comment]
This is not a bug, it is completely intended as per https://www.worldcubeassociation.org/regulations/#4b3a

The background is that for blindfolded events, the participants should not be able to "guess" the orientation that the puzzle is in due to the nature of most blindfolded solving methods relying on a fixed orientation.
For 3x3 Blindfolded and 5x5 Blindfolded, you can observe the same behaviour in the form of "extra-wide" moves at the end (Rw for 3x3, 3Rw for 5x5) that permute the fixed centers. 4 is an even number so there are no fixed centers and rotations are used instead.

**Comment by eriktks** [comment]
It is not possible to guess the orientation of a properly-scrambled even-sized cube because it has no fixed centers. The extra-wide moves that are added to a 3x3 Blindfolded scramble are already part of a regular 4x4 scramble. The cube rotations added by TNoodle for 4x4 Blindfolded make no sense. But thanks for the link to the rules. I will ask the people over there.
