### ISSUE TITLE
Generating scrambles on Firefox returns `null`

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/tnoodle#887]
Report thread: "Tnoodle 1.2.1 multi-blind scrambles selection"

> Thanks for the information. I would also like to add that attempting to generate on Mozilla browser results in null error (attached picture for reference). I'm sure You already knew about it too, and fix it in the future version. I successfully used Google Chrome instead.

**Comment by gregorbg** [comment]
@viroulep (tagging you here because you voluntarily closed the other issue)

I can confirm that this is an issue on Firefox, however I can not reliably reproduce it. From some preliminary testing, it seems that in >80% of cases, scramble generation works as expected and it only occasionally fails with the mysterious error.

By the way, I booted TNoodle in development mode and even then I don't get any additional error output. Neither the React frontend nor the backend print any logs indicating that anything went wrong.
If I instruct the message interceptor (which is responsible for showing the red pop-up error bar at the top) to log each and every error it encounters to the JS console, nothing happens.

All in all, quite strange and even though I can confirm it _does_ occur, it is incredibly hard for me to reproduce.
Did you find any way to reliably reproduce this?

**Comment by viroulep** [comment]
I have not been able to generate *any* scrambles for an existing competition in Firefox just yet, so it's definitely 100% reproducible for me.
Do you have the version 121 too?

I'm not sure how easy it is to run firefox in a docker container, but I would assume that starting from a clean debian bookworm, and then installing the default-jre as well as [firefox-mozilla-build](https://sourceforge.net/p/ubuntuzilla/wiki/Main_Page/) would put you pretty much in my setup (I've tested without extensions enabled).
I actually don't know if `firefox-esr` is impacted too, but that would be even easier to test in docker since it does not even require configuring another apt source.

Hippolyte also encountered the same error using Edge on Windows, I'll try to get more information and put them here!

**Comment by viroulep** [comment]
Sorry I got it wrong, it worked on Edge for Hippolyte, but it crashes consistently on Firefox 121 on Windows 10!

**Comment by dunkOnIT** [comment]
Fixed in 1.2.2
